/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.skala.db.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class City implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long cityId;
    private String city;
    private Long countryId;
    private LocalDateTime lastUpdate;

    public City() {}

    public City(City value) {
        this.cityId = value.cityId;
        this.city = value.city;
        this.countryId = value.countryId;
        this.lastUpdate = value.lastUpdate;
    }

    public City(
        Long cityId,
        String city,
        Long countryId,
        LocalDateTime lastUpdate
    ) {
        this.cityId = cityId;
        this.city = city;
        this.countryId = countryId;
        this.lastUpdate = lastUpdate;
    }

    /**
     * Getter for <code>public.city.city_id</code>.
     */
    public Long getCityId() {
        return this.cityId;
    }

    /**
     * Setter for <code>public.city.city_id</code>.
     */
    public void setCityId(Long cityId) {
        this.cityId = cityId;
    }

    /**
     * Getter for <code>public.city.city</code>.
     */
    public String getCity() {
        return this.city;
    }

    /**
     * Setter for <code>public.city.city</code>.
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for <code>public.city.country_id</code>.
     */
    public Long getCountryId() {
        return this.countryId;
    }

    /**
     * Setter for <code>public.city.country_id</code>.
     */
    public void setCountryId(Long countryId) {
        this.countryId = countryId;
    }

    /**
     * Getter for <code>public.city.last_update</code>.
     */
    public LocalDateTime getLastUpdate() {
        return this.lastUpdate;
    }

    /**
     * Setter for <code>public.city.last_update</code>.
     */
    public void setLastUpdate(LocalDateTime lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
}
