/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.kotlin.db.indexes


import org.jooq.Index
import org.jooq.demo.kotlin.db.tables.Actor
import org.jooq.demo.kotlin.db.tables.Address
import org.jooq.demo.kotlin.db.tables.City
import org.jooq.demo.kotlin.db.tables.Customer
import org.jooq.demo.kotlin.db.tables.Film
import org.jooq.demo.kotlin.db.tables.FilmActor
import org.jooq.demo.kotlin.db.tables.Inventory
import org.jooq.demo.kotlin.db.tables.Payment
import org.jooq.demo.kotlin.db.tables.Rental
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val ACTOR_IDX_ACTOR_LAST_NAME: Index = Internal.createIndex(DSL.name("idx_actor_last_name"), Actor.ACTOR, arrayOf(Actor.ACTOR.LAST_NAME), false)
val CUSTOMER_IDX_FK_ADDRESS_ID: Index = Internal.createIndex(DSL.name("idx_fk_address_id"), Customer.CUSTOMER, arrayOf(Customer.CUSTOMER.ADDRESS_ID), false)
val ADDRESS_IDX_FK_CITY_ID: Index = Internal.createIndex(DSL.name("idx_fk_city_id"), Address.ADDRESS, arrayOf(Address.ADDRESS.CITY_ID), false)
val CITY_IDX_FK_COUNTRY_ID: Index = Internal.createIndex(DSL.name("idx_fk_country_id"), City.CITY, arrayOf(City.CITY.COUNTRY_ID), false)
val PAYMENT_IDX_FK_CUSTOMER_ID: Index = Internal.createIndex(DSL.name("idx_fk_customer_id"), Payment.PAYMENT, arrayOf(Payment.PAYMENT.CUSTOMER_ID), false)
val FILM_ACTOR_IDX_FK_FILM_ID: Index = Internal.createIndex(DSL.name("idx_fk_film_id"), FilmActor.FILM_ACTOR, arrayOf(FilmActor.FILM_ACTOR.FILM_ID), false)
val RENTAL_IDX_FK_INVENTORY_ID: Index = Internal.createIndex(DSL.name("idx_fk_inventory_id"), Rental.RENTAL, arrayOf(Rental.RENTAL.INVENTORY_ID), false)
val FILM_IDX_FK_LANGUAGE_ID: Index = Internal.createIndex(DSL.name("idx_fk_language_id"), Film.FILM, arrayOf(Film.FILM.LANGUAGE_ID), false)
val FILM_IDX_FK_ORIGINAL_LANGUAGE_ID: Index = Internal.createIndex(DSL.name("idx_fk_original_language_id"), Film.FILM, arrayOf(Film.FILM.ORIGINAL_LANGUAGE_ID), false)
val PAYMENT_IDX_FK_STAFF_ID: Index = Internal.createIndex(DSL.name("idx_fk_staff_id"), Payment.PAYMENT, arrayOf(Payment.PAYMENT.STAFF_ID), false)
val CUSTOMER_IDX_FK_STORE_ID: Index = Internal.createIndex(DSL.name("idx_fk_store_id"), Customer.CUSTOMER, arrayOf(Customer.CUSTOMER.STORE_ID), false)
val CUSTOMER_IDX_LAST_NAME: Index = Internal.createIndex(DSL.name("idx_last_name"), Customer.CUSTOMER, arrayOf(Customer.CUSTOMER.LAST_NAME), false)
val INVENTORY_IDX_STORE_ID_FILM_ID: Index = Internal.createIndex(DSL.name("idx_store_id_film_id"), Inventory.INVENTORY, arrayOf(Inventory.INVENTORY.STORE_ID, Inventory.INVENTORY.FILM_ID), false)
val FILM_IDX_TITLE: Index = Internal.createIndex(DSL.name("idx_title"), Film.FILM, arrayOf(Film.FILM.TITLE), false)
