/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.kotlin.db.tables.records


import org.jooq.demo.kotlin.db.tables.FilmInStock
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class FilmInStockRecord() : TableRecordImpl<FilmInStockRecord>(FilmInStock.FILM_IN_STOCK) {

    open var pFilmCount: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    /**
     * Create a detached, initialised FilmInStockRecord
     */
    constructor(pFilmCount: Int? = null): this() {
        this.pFilmCount = pFilmCount
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised FilmInStockRecord
     */
    constructor(value: org.jooq.demo.kotlin.db.tables.pojos.FilmInStock?): this() {
        if (value != null) {
            this.pFilmCount = value.pFilmCount
            resetTouchedOnNotNull()
        }
    }
}
