/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.kotlin.db.enums


import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema
import org.jooq.demo.kotlin.db.Public


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class MpaaRating(@get:JvmName("literal") public val literal: String) : EnumType {
    G("G"),
    PG("PG"),
    `PG-13`("PG-13"),
    R("R"),
    `NC-17`("NC-17");
    public override fun getCatalog(): Catalog? = schema.catalog
    public override fun getSchema(): Schema = Public.PUBLIC
    public override fun getName(): String = "mpaa_rating"
    public override fun getLiteral(): String = literal
}
