@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.kotlin.db.domains


import org.jooq.Domain
import org.jooq.Record
import org.jooq.Schema
import org.jooq.demo.kotlin.db.Public
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.LazySchema
import org.jooq.impl.LazySupplier
import org.jooq.impl.SQLDataType



/**
 * The domain <code>public.year</code>.
 */
val YEAR: Domain<Int> = Internal.createDomain(
      schema()
    , DSL.name("year")
    , DSL.comment("")
    , SQLDataType.INTEGER
    , Internal.createCheck<Record>(null, null, "CHECK (((VALUE >= 1901) AND (VALUE <= 2155)))")
)

private fun schema(): Schema = LazySchema(DSL.name("public"), DSL.comment(""), LazySupplier { Public.PUBLIC })
