/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.kotlin.db.tables.records


import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.demo.kotlin.db.tables.City
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CityRecord() : UpdatableRecordImpl<CityRecord>(City.CITY) {

    open var cityId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var city: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var countryId: Long?
        set(value): Unit = set(2, value)
        get(): Long? = get(2) as Long?

    open var lastUpdate: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    /**
     * Create a detached, initialised CityRecord
     */
    constructor(cityId: Long? = null, city: String? = null, countryId: Long? = null, lastUpdate: LocalDateTime? = null): this() {
        this.cityId = cityId
        this.city = city
        this.countryId = countryId
        this.lastUpdate = lastUpdate
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised CityRecord
     */
    constructor(value: org.jooq.demo.kotlin.db.tables.pojos.City?): this() {
        if (value != null) {
            this.cityId = value.cityId
            this.city = value.city
            this.countryId = value.countryId
            this.lastUpdate = value.lastUpdate
            resetTouchedOnNotNull()
        }
    }
}
