/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.kotlin.db.tables.records


import java.time.LocalDateTime

import org.jooq.Field
import org.jooq.Record2
import org.jooq.Record3
import org.jooq.Row3
import org.jooq.demo.kotlin.db.tables.FilmActor
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class FilmActorRecord() : UpdatableRecordImpl<FilmActorRecord>(FilmActor.FILM_ACTOR), Record3<Long?, Long?, LocalDateTime?> {

    open var actorId: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var filmId: Long?
        set(value): Unit = set(1, value)
        get(): Long? = get(1) as Long?

    open var lastUpdate: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    public override fun key(): Record2<Long?, Long?> = super.key() as Record2<Long?, Long?>

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    public override fun fieldsRow(): Row3<Long?, Long?, LocalDateTime?> = super.fieldsRow() as Row3<Long?, Long?, LocalDateTime?>
    public override fun valuesRow(): Row3<Long?, Long?, LocalDateTime?> = super.valuesRow() as Row3<Long?, Long?, LocalDateTime?>
    public override fun field1(): Field<Long?> = FilmActor.FILM_ACTOR.ACTOR_ID
    public override fun field2(): Field<Long?> = FilmActor.FILM_ACTOR.FILM_ID
    public override fun field3(): Field<LocalDateTime?> = FilmActor.FILM_ACTOR.LAST_UPDATE
    public override fun component1(): Long? = actorId
    public override fun component2(): Long? = filmId
    public override fun component3(): LocalDateTime? = lastUpdate
    public override fun value1(): Long? = actorId
    public override fun value2(): Long? = filmId
    public override fun value3(): LocalDateTime? = lastUpdate

    public override fun value1(value: Long?): FilmActorRecord {
        set(0, value)
        return this
    }

    public override fun value2(value: Long?): FilmActorRecord {
        set(1, value)
        return this
    }

    public override fun value3(value: LocalDateTime?): FilmActorRecord {
        set(2, value)
        return this
    }

    public override fun values(value1: Long?, value2: Long?, value3: LocalDateTime?): FilmActorRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        return this
    }

    /**
     * Create a detached, initialised FilmActorRecord
     */
    constructor(actorId: Long? = null, filmId: Long? = null, lastUpdate: LocalDateTime? = null): this() {
        this.actorId = actorId
        this.filmId = filmId
        this.lastUpdate = lastUpdate
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised FilmActorRecord
     */
    constructor(value: org.jooq.demo.kotlin.db.tables.pojos.FilmActor?): this() {
        if (value != null) {
            this.actorId = value.actorId
            this.filmId = value.filmId
            this.lastUpdate = value.lastUpdate
            resetChangedOnNotNull()
        }
    }
}
