/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.kotlin.db.tables.records


import org.jooq.Field
import org.jooq.Record8
import org.jooq.Row8
import org.jooq.demo.kotlin.db.tables.StaffList
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class StaffListRecord() : TableRecordImpl<StaffListRecord>(StaffList.STAFF_LIST), Record8<Long?, String?, String?, String?, String?, String?, String?, Long?> {

    open var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open var name: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var address: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var zipCode: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var phone: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var city: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    open var country: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open var sid: Long?
        set(value): Unit = set(7, value)
        get(): Long? = get(7) as Long?

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    public override fun fieldsRow(): Row8<Long?, String?, String?, String?, String?, String?, String?, Long?> = super.fieldsRow() as Row8<Long?, String?, String?, String?, String?, String?, String?, Long?>
    public override fun valuesRow(): Row8<Long?, String?, String?, String?, String?, String?, String?, Long?> = super.valuesRow() as Row8<Long?, String?, String?, String?, String?, String?, String?, Long?>
    public override fun field1(): Field<Long?> = StaffList.STAFF_LIST.ID
    public override fun field2(): Field<String?> = StaffList.STAFF_LIST.NAME
    public override fun field3(): Field<String?> = StaffList.STAFF_LIST.ADDRESS
    public override fun field4(): Field<String?> = org.jooq.demo.kotlin.db.tables.StaffList.STAFF_LIST.`ZIP CODE`
    public override fun field5(): Field<String?> = StaffList.STAFF_LIST.PHONE
    public override fun field6(): Field<String?> = StaffList.STAFF_LIST.CITY
    public override fun field7(): Field<String?> = StaffList.STAFF_LIST.COUNTRY
    public override fun field8(): Field<Long?> = StaffList.STAFF_LIST.SID
    public override fun component1(): Long? = id
    public override fun component2(): String? = name
    public override fun component3(): String? = address
    public override fun component4(): String? = zipCode
    public override fun component5(): String? = phone
    public override fun component6(): String? = city
    public override fun component7(): String? = country
    public override fun component8(): Long? = sid
    public override fun value1(): Long? = id
    public override fun value2(): String? = name
    public override fun value3(): String? = address
    public override fun value4(): String? = zipCode
    public override fun value5(): String? = phone
    public override fun value6(): String? = city
    public override fun value7(): String? = country
    public override fun value8(): Long? = sid

    public override fun value1(value: Long?): StaffListRecord {
        set(0, value)
        return this
    }

    public override fun value2(value: String?): StaffListRecord {
        set(1, value)
        return this
    }

    public override fun value3(value: String?): StaffListRecord {
        set(2, value)
        return this
    }

    public override fun value4(value: String?): StaffListRecord {
        set(3, value)
        return this
    }

    public override fun value5(value: String?): StaffListRecord {
        set(4, value)
        return this
    }

    public override fun value6(value: String?): StaffListRecord {
        set(5, value)
        return this
    }

    public override fun value7(value: String?): StaffListRecord {
        set(6, value)
        return this
    }

    public override fun value8(value: Long?): StaffListRecord {
        set(7, value)
        return this
    }

    public override fun values(value1: Long?, value2: String?, value3: String?, value4: String?, value5: String?, value6: String?, value7: String?, value8: Long?): StaffListRecord {
        this.value1(value1)
        this.value2(value2)
        this.value3(value3)
        this.value4(value4)
        this.value5(value5)
        this.value6(value6)
        this.value7(value7)
        this.value8(value8)
        return this
    }

    /**
     * Create a detached, initialised StaffListRecord
     */
    constructor(id: Long? = null, name: String? = null, address: String? = null, zipCode: String? = null, phone: String? = null, city: String? = null, country: String? = null, sid: Long? = null): this() {
        this.id = id
        this.name = name
        this.address = address
        this.zipCode = zipCode
        this.phone = phone
        this.city = city
        this.country = country
        this.sid = sid
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised StaffListRecord
     */
    constructor(value: org.jooq.demo.kotlin.db.tables.pojos.StaffList?): this() {
        if (value != null) {
            this.id = value.id
            this.name = value.name
            this.address = value.address
            this.zipCode = value.zipCode
            this.phone = value.phone
            this.city = value.city
            this.country = value.country
            this.sid = value.sid
            resetChangedOnNotNull()
        }
    }
}
