/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.kotlin.db.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class FilmNotInStock(
    var pFilmCount: Int? = null
): Serializable {

}
