/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.java.db;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.demo.java.db.tables.Actor;
import org.jooq.demo.java.db.tables.Address;
import org.jooq.demo.java.db.tables.Category;
import org.jooq.demo.java.db.tables.City;
import org.jooq.demo.java.db.tables.Country;
import org.jooq.demo.java.db.tables.Customer;
import org.jooq.demo.java.db.tables.CustomerList;
import org.jooq.demo.java.db.tables.Film;
import org.jooq.demo.java.db.tables.FilmActor;
import org.jooq.demo.java.db.tables.FilmCategory;
import org.jooq.demo.java.db.tables.Inventory;
import org.jooq.demo.java.db.tables.Language;
import org.jooq.demo.java.db.tables.Payment;
import org.jooq.demo.java.db.tables.Rental;
import org.jooq.demo.java.db.tables.SalesByFilmCategory;
import org.jooq.demo.java.db.tables.SalesByStore;
import org.jooq.demo.java.db.tables.Staff;
import org.jooq.demo.java.db.tables.StaffList;
import org.jooq.demo.java.db.tables.Store;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.actor</code>.
     */
    public final Actor ACTOR = Actor.ACTOR;

    /**
     * The table <code>public.address</code>.
     */
    public final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>public.category</code>.
     */
    public final Category CATEGORY = Category.CATEGORY;

    /**
     * The table <code>public.city</code>.
     */
    public final City CITY = City.CITY;

    /**
     * The table <code>public.country</code>.
     */
    public final Country COUNTRY = Country.COUNTRY;

    /**
     * The table <code>public.customer</code>.
     */
    public final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>public.customer_list</code>.
     */
    public final CustomerList CUSTOMER_LIST = CustomerList.CUSTOMER_LIST;

    /**
     * The table <code>public.film</code>.
     */
    public final Film FILM = Film.FILM;

    /**
     * The table <code>public.film_actor</code>.
     */
    public final FilmActor FILM_ACTOR = FilmActor.FILM_ACTOR;

    /**
     * The table <code>public.film_category</code>.
     */
    public final FilmCategory FILM_CATEGORY = FilmCategory.FILM_CATEGORY;

    /**
     * The table <code>public.inventory</code>.
     */
    public final Inventory INVENTORY = Inventory.INVENTORY;

    /**
     * The table <code>public.language</code>.
     */
    public final Language LANGUAGE = Language.LANGUAGE;

    /**
     * The table <code>public.payment</code>.
     */
    public final Payment PAYMENT = Payment.PAYMENT;

    /**
     * The table <code>public.rental</code>.
     */
    public final Rental RENTAL = Rental.RENTAL;

    /**
     * The table <code>public.sales_by_film_category</code>.
     */
    public final SalesByFilmCategory SALES_BY_FILM_CATEGORY = SalesByFilmCategory.SALES_BY_FILM_CATEGORY;

    /**
     * The table <code>public.sales_by_store</code>.
     */
    public final SalesByStore SALES_BY_STORE = SalesByStore.SALES_BY_STORE;

    /**
     * The table <code>public.staff</code>.
     */
    public final Staff STAFF = Staff.STAFF;

    /**
     * The table <code>public.staff_list</code>.
     */
    public final StaffList STAFF_LIST = StaffList.STAFF_LIST;

    /**
     * The table <code>public.store</code>.
     */
    public final Store STORE = Store.STORE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.asList(
            Sequences.ACTOR_ACTOR_ID_SEQ,
            Sequences.ADDRESS_ADDRESS_ID_SEQ,
            Sequences.CATEGORY_CATEGORY_ID_SEQ,
            Sequences.CITY_CITY_ID_SEQ,
            Sequences.COUNTRY_COUNTRY_ID_SEQ,
            Sequences.CUSTOMER_CUSTOMER_ID_SEQ,
            Sequences.FILM_FILM_ID_SEQ,
            Sequences.INVENTORY_INVENTORY_ID_SEQ,
            Sequences.LANGUAGE_LANGUAGE_ID_SEQ,
            Sequences.PAYMENT_PAYMENT_ID_SEQ,
            Sequences.RENTAL_RENTAL_ID_SEQ,
            Sequences.STAFF_STAFF_ID_SEQ,
            Sequences.STORE_STORE_ID_SEQ
        );
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Actor.ACTOR,
            Address.ADDRESS,
            Category.CATEGORY,
            City.CITY,
            Country.COUNTRY,
            Customer.CUSTOMER,
            CustomerList.CUSTOMER_LIST,
            Film.FILM,
            FilmActor.FILM_ACTOR,
            FilmCategory.FILM_CATEGORY,
            Inventory.INVENTORY,
            Language.LANGUAGE,
            Payment.PAYMENT,
            Rental.RENTAL,
            SalesByFilmCategory.SALES_BY_FILM_CATEGORY,
            SalesByStore.SALES_BY_STORE,
            Staff.STAFF,
            StaffList.STAFF_LIST,
            Store.STORE
        );
    }
}
