/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.kotlin.db.tables.daos


import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.demo.kotlin.db.tables.Actor
import org.jooq.demo.kotlin.db.tables.records.ActorRecord
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class ActorDao(configuration: Configuration?) : DAOImpl<ActorRecord, org.jooq.demo.kotlin.db.tables.pojos.Actor, Long>(Actor.ACTOR, org.jooq.demo.kotlin.db.tables.pojos.Actor::class.java, configuration) {

    /**
     * Create a new ActorDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: org.jooq.demo.kotlin.db.tables.pojos.Actor): Long? = o.actorId

    /**
     * Fetch records that have <code>actor_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfActorId(lowerInclusive: Long?, upperInclusive: Long?): List<org.jooq.demo.kotlin.db.tables.pojos.Actor> = fetchRange(Actor.ACTOR.ACTOR_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>actor_id IN (values)</code>
     */
    fun fetchByActorId(vararg values: Long): List<org.jooq.demo.kotlin.db.tables.pojos.Actor> = fetch(Actor.ACTOR.ACTOR_ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>actor_id = value</code>
     */
    fun fetchOneByActorId(value: Long): org.jooq.demo.kotlin.db.tables.pojos.Actor? = fetchOne(Actor.ACTOR.ACTOR_ID, value)

    /**
     * Fetch records that have <code>first_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfFirstName(lowerInclusive: String?, upperInclusive: String?): List<org.jooq.demo.kotlin.db.tables.pojos.Actor> = fetchRange(Actor.ACTOR.FIRST_NAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>first_name IN (values)</code>
     */
    fun fetchByFirstName(vararg values: String): List<org.jooq.demo.kotlin.db.tables.pojos.Actor> = fetch(Actor.ACTOR.FIRST_NAME, *values)

    /**
     * Fetch records that have <code>last_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfLastName(lowerInclusive: String?, upperInclusive: String?): List<org.jooq.demo.kotlin.db.tables.pojos.Actor> = fetchRange(Actor.ACTOR.LAST_NAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>last_name IN (values)</code>
     */
    fun fetchByLastName(vararg values: String): List<org.jooq.demo.kotlin.db.tables.pojos.Actor> = fetch(Actor.ACTOR.LAST_NAME, *values)

    /**
     * Fetch records that have <code>last_update BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfLastUpdate(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<org.jooq.demo.kotlin.db.tables.pojos.Actor> = fetchRange(Actor.ACTOR.LAST_UPDATE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>last_update IN (values)</code>
     */
    fun fetchByLastUpdate(vararg values: LocalDateTime): List<org.jooq.demo.kotlin.db.tables.pojos.Actor> = fetch(Actor.ACTOR.LAST_UPDATE, *values)
}
