/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.kotlin.db.tables.daos


import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.demo.kotlin.db.tables.Category
import org.jooq.demo.kotlin.db.tables.records.CategoryRecord
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CategoryDao(configuration: Configuration?) : DAOImpl<CategoryRecord, org.jooq.demo.kotlin.db.tables.pojos.Category, Long>(Category.CATEGORY, org.jooq.demo.kotlin.db.tables.pojos.Category::class.java, configuration) {

    /**
     * Create a new CategoryDao without any configuration
     */
    constructor(): this(null)

    public override fun getId(o: org.jooq.demo.kotlin.db.tables.pojos.Category): Long? = o.categoryId

    /**
     * Fetch records that have <code>category_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCategoryId(lowerInclusive: Long?, upperInclusive: Long?): List<org.jooq.demo.kotlin.db.tables.pojos.Category> = fetchRange(Category.CATEGORY.CATEGORY_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>category_id IN (values)</code>
     */
    fun fetchByCategoryId(vararg values: Long): List<org.jooq.demo.kotlin.db.tables.pojos.Category> = fetch(Category.CATEGORY.CATEGORY_ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>category_id = value</code>
     */
    fun fetchOneByCategoryId(value: Long): org.jooq.demo.kotlin.db.tables.pojos.Category? = fetchOne(Category.CATEGORY.CATEGORY_ID, value)

    /**
     * Fetch records that have <code>name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfName(lowerInclusive: String?, upperInclusive: String?): List<org.jooq.demo.kotlin.db.tables.pojos.Category> = fetchRange(Category.CATEGORY.NAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    fun fetchByName(vararg values: String): List<org.jooq.demo.kotlin.db.tables.pojos.Category> = fetch(Category.CATEGORY.NAME, *values)

    /**
     * Fetch records that have <code>last_update BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfLastUpdate(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<org.jooq.demo.kotlin.db.tables.pojos.Category> = fetchRange(Category.CATEGORY.LAST_UPDATE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>last_update IN (values)</code>
     */
    fun fetchByLastUpdate(vararg values: LocalDateTime): List<org.jooq.demo.kotlin.db.tables.pojos.Category> = fetch(Category.CATEGORY.LAST_UPDATE, *values)
}
