/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.kotlin.db.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class Address(
    var addressId: Long? = null,
    var address: String? = null,
    var address2: String? = null,
    var district: String? = null,
    var cityId: Long? = null,
    var postalCode: String? = null,
    var phone: String? = null,
    var lastUpdate: LocalDateTime? = null
): Serializable {

}
