/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.kotlin.db.tables.pojos


import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class CustomerList(
    var id: Long? = null,
    var name: String? = null,
    var address: String? = null,
    var zipCode: String? = null,
    var phone: String? = null,
    var city: String? = null,
    var country: String? = null,
    var notes: String? = null,
    var sid: Long? = null
): Serializable {

}
