/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.kotlin.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;

import org.jooq.demo.kotlin.db.enums.MpaaRating;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FilmList implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long fid;
    private String title;
    private String description;
    private String category;
    private BigDecimal price;
    private Short length;
    private MpaaRating rating;
    private String actors;

    public FilmList() {}

    public FilmList(FilmList value) {
        this.fid = value.fid;
        this.title = value.title;
        this.description = value.description;
        this.category = value.category;
        this.price = value.price;
        this.length = value.length;
        this.rating = value.rating;
        this.actors = value.actors;
    }

    public FilmList(
        Long fid,
        String title,
        String description,
        String category,
        BigDecimal price,
        Short length,
        MpaaRating rating,
        String actors
    ) {
        this.fid = fid;
        this.title = title;
        this.description = description;
        this.category = category;
        this.price = price;
        this.length = length;
        this.rating = rating;
        this.actors = actors;
    }

    /**
     * Getter for <code>public.film_list.fid</code>.
     */
    public Long getFid() {
        return this.fid;
    }

    /**
     * Setter for <code>public.film_list.fid</code>.
     */
    public void setFid(Long fid) {
        this.fid = fid;
    }

    /**
     * Getter for <code>public.film_list.title</code>.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Setter for <code>public.film_list.title</code>.
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Getter for <code>public.film_list.description</code>.
     */
    public String getDescription() {
        return this.description;
    }

    /**
     * Setter for <code>public.film_list.description</code>.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Getter for <code>public.film_list.category</code>.
     */
    public String getCategory() {
        return this.category;
    }

    /**
     * Setter for <code>public.film_list.category</code>.
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * Getter for <code>public.film_list.price</code>.
     */
    public BigDecimal getPrice() {
        return this.price;
    }

    /**
     * Setter for <code>public.film_list.price</code>.
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * Getter for <code>public.film_list.length</code>.
     */
    public Short getLength() {
        return this.length;
    }

    /**
     * Setter for <code>public.film_list.length</code>.
     */
    public void setLength(Short length) {
        this.length = length;
    }

    /**
     * Getter for <code>public.film_list.rating</code>.
     */
    public MpaaRating getRating() {
        return this.rating;
    }

    /**
     * Setter for <code>public.film_list.rating</code>.
     */
    public void setRating(MpaaRating rating) {
        this.rating = rating;
    }

    /**
     * Getter for <code>public.film_list.actors</code>.
     */
    public String getActors() {
        return this.actors;
    }

    /**
     * Setter for <code>public.film_list.actors</code>.
     */
    public void setActors(String actors) {
        this.actors = actors;
    }
}
