/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.kotlin.db.tables.pojos


import java.io.Serializable
import java.math.BigDecimal


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class SalesByStore(
    var store: String? = null,
    var manager: String? = null,
    var totalSales: BigDecimal? = null
): Serializable {

}
