/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.kotlin.db.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffList implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String name;
    private String address;
    private String zipCode;
    private String phone;
    private String city;
    private String country;
    private Long sid;

    public StaffList() {}

    public StaffList(StaffList value) {
        this.id = value.id;
        this.name = value.name;
        this.address = value.address;
        this.zipCode = value.zipCode;
        this.phone = value.phone;
        this.city = value.city;
        this.country = value.country;
        this.sid = value.sid;
    }

    public StaffList(
        Long id,
        String name,
        String address,
        String zipCode,
        String phone,
        String city,
        String country,
        Long sid
    ) {
        this.id = id;
        this.name = name;
        this.address = address;
        this.zipCode = zipCode;
        this.phone = phone;
        this.city = city;
        this.country = country;
        this.sid = sid;
    }

    /**
     * Getter for <code>public.staff_list.id</code>.
     */
    public Long getId() {
        return this.id;
    }

    /**
     * Setter for <code>public.staff_list.id</code>.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Getter for <code>public.staff_list.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Setter for <code>public.staff_list.name</code>.
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for <code>public.staff_list.address</code>.
     */
    public String getAddress() {
        return this.address;
    }

    /**
     * Setter for <code>public.staff_list.address</code>.
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Getter for <code>public.staff_list.zip code</code>.
     */
    public String getZipCode() {
        return this.zipCode;
    }

    /**
     * Setter for <code>public.staff_list.zip code</code>.
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode;
    }

    /**
     * Getter for <code>public.staff_list.phone</code>.
     */
    public String getPhone() {
        return this.phone;
    }

    /**
     * Setter for <code>public.staff_list.phone</code>.
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * Getter for <code>public.staff_list.city</code>.
     */
    public String getCity() {
        return this.city;
    }

    /**
     * Setter for <code>public.staff_list.city</code>.
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * Getter for <code>public.staff_list.country</code>.
     */
    public String getCountry() {
        return this.country;
    }

    /**
     * Setter for <code>public.staff_list.country</code>.
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * Getter for <code>public.staff_list.sid</code>.
     */
    public Long getSid() {
        return this.sid;
    }

    /**
     * Setter for <code>public.staff_list.sid</code>.
     */
    public void setSid(Long sid) {
        this.sid = sid;
    }
}
