/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.skala.db.tables.daos


import java.lang.Long
import java.math.BigDecimal
import java.time.LocalDateTime
import java.util.Collection
import java.util.List

import org.jooq.Configuration
import org.jooq.demo.skala.db.tables.Payment
import org.jooq.demo.skala.db.tables.records.PaymentRecord
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
class PaymentDao(configuration: Configuration) extends DAOImpl[PaymentRecord, org.jooq.demo.skala.db.tables.pojos.Payment, Long](Payment.PAYMENT, classOf[org.jooq.demo.skala.db.tables.pojos.Payment], configuration) {

  /**
   * Create a new PaymentDao without any configuration
   */
  def this() = this(null)

  override def getId(o: org.jooq.demo.skala.db.tables.pojos.Payment): Long = o.getPaymentId
  override def insert(obj: org.jooq.demo.skala.db.tables.pojos.Payment): Unit = super.insert(obj)
  override def insert(objs: org.jooq.demo.skala.db.tables.pojos.Payment*): Unit = super.insert(objs:_*)
  override def insert(objs: Collection[org.jooq.demo.skala.db.tables.pojos.Payment]): Unit = super.insert(objs)
  override def update(obj: org.jooq.demo.skala.db.tables.pojos.Payment): Unit = super.update(obj)
  override def update(objs: org.jooq.demo.skala.db.tables.pojos.Payment*): Unit = super.update(objs:_*)
  override def update(objs: Collection[org.jooq.demo.skala.db.tables.pojos.Payment]): Unit = super.update(objs)
  override def merge(obj: org.jooq.demo.skala.db.tables.pojos.Payment): Unit = super.merge(obj)
  override def merge(objs: org.jooq.demo.skala.db.tables.pojos.Payment*): Unit = super.merge(objs:_*)
  override def merge(objs: Collection[org.jooq.demo.skala.db.tables.pojos.Payment]): Unit = super.merge(objs)
  override def delete(obj: org.jooq.demo.skala.db.tables.pojos.Payment): Unit = super.delete(obj)
  override def delete(objs: org.jooq.demo.skala.db.tables.pojos.Payment*): Unit = super.delete(objs:_*)
  override def delete(objs: Collection[org.jooq.demo.skala.db.tables.pojos.Payment]): Unit = super.delete(objs)
  override def deleteById(id: Long): Unit = super.deleteById(id)
  override def deleteById(ids: Long*): Unit = super.deleteById(ids:_*)
  override def deleteById(ids: Collection[Long]): Unit = super.deleteById(ids)

  /**
   * Fetch records that have <code>payment_id BETWEEN lowerInclusive AND
   * upperInclusive</code>
   */
  def fetchRangeOfPaymentId(lowerInclusive: Long, upperInclusive: Long): List[org.jooq.demo.skala.db.tables.pojos.Payment] = fetchRange(Payment.PAYMENT.PAYMENT_ID, lowerInclusive, upperInclusive)

  /**
   * Fetch records that have <code>payment_id IN (values)</code>
   */
  def fetchByPaymentId(values: Long*): List[org.jooq.demo.skala.db.tables.pojos.Payment] = fetch(Payment.PAYMENT.PAYMENT_ID, values:_*)

  /**
   * Fetch a unique record that has <code>payment_id = value</code>
   */
  def fetchOneByPaymentId(value: Long): org.jooq.demo.skala.db.tables.pojos.Payment = fetchOne(Payment.PAYMENT.PAYMENT_ID, value)

  /**
   * Fetch records that have <code>customer_id BETWEEN lowerInclusive AND
   * upperInclusive</code>
   */
  def fetchRangeOfCustomerId(lowerInclusive: Long, upperInclusive: Long): List[org.jooq.demo.skala.db.tables.pojos.Payment] = fetchRange(Payment.PAYMENT.CUSTOMER_ID, lowerInclusive, upperInclusive)

  /**
   * Fetch records that have <code>customer_id IN (values)</code>
   */
  def fetchByCustomerId(values: Long*): List[org.jooq.demo.skala.db.tables.pojos.Payment] = fetch(Payment.PAYMENT.CUSTOMER_ID, values:_*)

  /**
   * Fetch records that have <code>staff_id BETWEEN lowerInclusive AND
   * upperInclusive</code>
   */
  def fetchRangeOfStaffId(lowerInclusive: Long, upperInclusive: Long): List[org.jooq.demo.skala.db.tables.pojos.Payment] = fetchRange(Payment.PAYMENT.STAFF_ID, lowerInclusive, upperInclusive)

  /**
   * Fetch records that have <code>staff_id IN (values)</code>
   */
  def fetchByStaffId(values: Long*): List[org.jooq.demo.skala.db.tables.pojos.Payment] = fetch(Payment.PAYMENT.STAFF_ID, values:_*)

  /**
   * Fetch records that have <code>rental_id BETWEEN lowerInclusive AND
   * upperInclusive</code>
   */
  def fetchRangeOfRentalId(lowerInclusive: Long, upperInclusive: Long): List[org.jooq.demo.skala.db.tables.pojos.Payment] = fetchRange(Payment.PAYMENT.RENTAL_ID, lowerInclusive, upperInclusive)

  /**
   * Fetch records that have <code>rental_id IN (values)</code>
   */
  def fetchByRentalId(values: Long*): List[org.jooq.demo.skala.db.tables.pojos.Payment] = fetch(Payment.PAYMENT.RENTAL_ID, values:_*)

  /**
   * Fetch records that have <code>amount BETWEEN lowerInclusive AND
   * upperInclusive</code>
   */
  def fetchRangeOfAmount(lowerInclusive: BigDecimal, upperInclusive: BigDecimal): List[org.jooq.demo.skala.db.tables.pojos.Payment] = fetchRange(Payment.PAYMENT.AMOUNT, lowerInclusive, upperInclusive)

  /**
   * Fetch records that have <code>amount IN (values)</code>
   */
  def fetchByAmount(values: BigDecimal*): List[org.jooq.demo.skala.db.tables.pojos.Payment] = fetch(Payment.PAYMENT.AMOUNT, values:_*)

  /**
   * Fetch records that have <code>payment_date BETWEEN lowerInclusive AND
   * upperInclusive</code>
   */
  def fetchRangeOfPaymentDate(lowerInclusive: LocalDateTime, upperInclusive: LocalDateTime): List[org.jooq.demo.skala.db.tables.pojos.Payment] = fetchRange(Payment.PAYMENT.PAYMENT_DATE, lowerInclusive, upperInclusive)

  /**
   * Fetch records that have <code>payment_date IN (values)</code>
   */
  def fetchByPaymentDate(values: LocalDateTime*): List[org.jooq.demo.skala.db.tables.pojos.Payment] = fetch(Payment.PAYMENT.PAYMENT_DATE, values:_*)
}
