/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.db.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public record SalesByStore(
    String     store,
    String     manager,
    BigDecimal totalSales
) implements Serializable {

    private static final long serialVersionUID = 1L;


    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final SalesByStore other = (SalesByStore) obj;
        if (this.store == null) {
            if (other.store != null)
                return false;
        }
        else if (!this.store.equals(other.store))
            return false;
        if (this.manager == null) {
            if (other.manager != null)
                return false;
        }
        else if (!this.manager.equals(other.manager))
            return false;
        if (this.totalSales == null) {
            if (other.totalSales != null)
                return false;
        }
        else if (!this.totalSales.equals(other.totalSales))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.store == null) ? 0 : this.store.hashCode());
        result = prime * result + ((this.manager == null) ? 0 : this.manager.hashCode());
        result = prime * result + ((this.totalSales == null) ? 0 : this.totalSales.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SalesByStore (");

        sb.append(store);
        sb.append(", ").append(manager);
        sb.append(", ").append(totalSales);

        sb.append(")");
        return sb.toString();
    }
}
