/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.skala.db.tables.pojos


import java.io.Serializable
import java.lang.Long
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
case class FilmActor(
  var actorId: Long,
  var filmId: Long,
  var lastUpdate: LocalDateTime
) extends Serializable {

  def this() = this(null, null, null)

  def this(value: FilmActor) = this(
    value.actorId,
    value.filmId,
    value.lastUpdate
  )

  /**
   * Getter for <code>public.film_actor.actor_id</code>.
   */
  def getActorId: Long = this.actorId

  /**
   * Setter for <code>public.film_actor.actor_id</code>.
   */
  def setActorId(actorId: Long): Unit = {
    this.actorId = actorId
  }

  /**
   * Getter for <code>public.film_actor.film_id</code>.
   */
  def getFilmId: Long = this.filmId

  /**
   * Setter for <code>public.film_actor.film_id</code>.
   */
  def setFilmId(filmId: Long): Unit = {
    this.filmId = filmId
  }

  /**
   * Getter for <code>public.film_actor.last_update</code>.
   */
  def getLastUpdate: LocalDateTime = this.lastUpdate

  /**
   * Setter for <code>public.film_actor.last_update</code>.
   */
  def setLastUpdate(lastUpdate: LocalDateTime): Unit = {
    this.lastUpdate = lastUpdate
  }
}
