/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.skala.db.tables


import java.lang.Boolean
import java.lang.Class
import java.lang.Long
import java.lang.String
import java.time.LocalDateTime
import java.util.Arrays
import java.util.Collection
import java.util.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.demo.skala.db.Indexes
import org.jooq.demo.skala.db.Keys
import org.jooq.demo.skala.db.Public
import org.jooq.demo.skala.db.tables.Actor.ActorPath
import org.jooq.demo.skala.db.tables.Film.FilmPath
import org.jooq.demo.skala.db.tables.records.FilmActorRecord
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl

import scala.Array


object FilmActor {

  /**
   * The reference instance of <code>public.film_actor</code>
   */
  val FILM_ACTOR = new FilmActor

  /**
   * A subtype implementing {@link Path} for simplified path-based joins.
   */
  class FilmActorPath(path: Table[? <: Record], childPath: ForeignKey[? <: Record, FilmActorRecord], parentPath: InverseForeignKey[? <: Record, FilmActorRecord]) extends FilmActor(path, childPath, parentPath) with Path[FilmActorRecord]
}

/**
 * This class is generated by jOOQ.
 */
class FilmActor(
  alias: Name,
  path: Table[? <: Record],
  childPath: ForeignKey[? <: Record, FilmActorRecord],
  parentPath: InverseForeignKey[? <: Record, FilmActorRecord],
  aliased: Table[FilmActorRecord],
  parameters: Array[ Field[?] ],
  where: Condition
)
extends TableImpl[FilmActorRecord](
  alias,
  Public.PUBLIC,
  path,
  childPath,
  parentPath,
  aliased,
  parameters,
  DSL.comment(""),
  TableOptions.table,
  where
) {

  /**
   * The class holding records for this type
   */
  override def getRecordType: Class[FilmActorRecord] = classOf[FilmActorRecord]

  /**
   * The column <code>public.film_actor.actor_id</code>.
   */
  val ACTOR_ID: TableField[FilmActorRecord, Long] = createField(DSL.name("actor_id"), SQLDataType.BIGINT.nullable(false), "")

  /**
   * The column <code>public.film_actor.film_id</code>.
   */
  val FILM_ID: TableField[FilmActorRecord, Long] = createField(DSL.name("film_id"), SQLDataType.BIGINT.nullable(false), "")

  /**
   * The column <code>public.film_actor.last_update</code>.
   */
  val LAST_UPDATE: TableField[FilmActorRecord, LocalDateTime] = createField(DSL.name("last_update"), SQLDataType.LOCALDATETIME(6).nullable(false).readonly(true).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), "")

  private def this(alias: Name, aliased: Table[FilmActorRecord]) = this(alias, null, null, null, aliased, null, null)
  private def this(alias: Name, aliased: Table[FilmActorRecord], where: Condition) = this(alias, null, null, null, aliased, null, where)

  /**
   * Create an aliased <code>public.film_actor</code> table reference
   */
  def this(alias: String) = this(DSL.name(alias), org.jooq.demo.skala.db.tables.FilmActor.FILM_ACTOR)

  /**
   * Create an aliased <code>public.film_actor</code> table reference
   */
  def this(alias: Name) = this(alias, org.jooq.demo.skala.db.tables.FilmActor.FILM_ACTOR)

  /**
   * Create a <code>public.film_actor</code> table reference
   */
  def this() = this(DSL.name("film_actor"), null)

  def this(path: Table[? <: Record], childPath: ForeignKey[? <: Record, FilmActorRecord], parentPath: InverseForeignKey[? <: Record, FilmActorRecord]) = this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, org.jooq.demo.skala.db.tables.FilmActor.FILM_ACTOR, null, null)

  override def getSchema: Schema = if (super.aliased()) null else Public.PUBLIC

  override def getIndexes: List[Index] = Arrays.asList[ Index ](Indexes.IDX_FK_FILM_ID)

  override def getPrimaryKey: UniqueKey[FilmActorRecord] = Keys.FILM_ACTOR_PKEY

  override def getReferences: List[ ForeignKey[FilmActorRecord, ?] ] = Arrays.asList[ ForeignKey[FilmActorRecord, ?] ](Keys.FILM_ACTOR__FILM_ACTOR_ACTOR_ID_FKEY, Keys.FILM_ACTOR__FILM_ACTOR_FILM_ID_FKEY)

  /**
   * Get the implicit join path to the <code>public.actor</code> table.
   */
  lazy val actor: ActorPath = { new ActorPath(this, Keys.FILM_ACTOR__FILM_ACTOR_ACTOR_ID_FKEY, null) }

  /**
   * Get the implicit join path to the <code>public.film</code> table.
   */
  lazy val film: FilmPath = { new FilmPath(this, Keys.FILM_ACTOR__FILM_ACTOR_FILM_ID_FKEY, null) }
  override def as(alias: String): FilmActor = new FilmActor(DSL.name(alias), this)
  override def as(alias: Name): FilmActor = new FilmActor(alias, this)
  override def as(alias: Table[?]): FilmActor = new FilmActor(alias.getQualifiedName(), this)

  /**
   * Rename this table
   */
  override def rename(name: String): FilmActor = new FilmActor(DSL.name(name), null)

  /**
   * Rename this table
   */
  override def rename(name: Name): FilmActor = new FilmActor(name, null)

  /**
   * Rename this table
   */
  override def rename(name: Table[?]): FilmActor = new FilmActor(name.getQualifiedName(), null)

  /**
   * Create an inline derived table from this table
   */
  override def where(condition: Condition): FilmActor = new FilmActor(getQualifiedName(), if (super.aliased()) this else null, condition)

  /**
   * Create an inline derived table from this table
   */
  override def where(conditions: Collection[? <: Condition]): FilmActor = where(DSL.and(conditions))

  /**
   * Create an inline derived table from this table
   */
  override def where(conditions: Condition*): FilmActor = where(DSL.and(conditions*))

  /**
   * Create an inline derived table from this table
   */
  override def where(condition: Field[Boolean]): FilmActor = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL override def where(condition: SQL): FilmActor = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL override def where(@Stringly.SQL condition: String): FilmActor = where(DSL.condition(condition))

  /**
   * Create an inline derived table from this table
   */
  @PlainSQL override def where(@Stringly.SQL condition: String, binds: AnyRef*): FilmActor = where(DSL.condition(condition, binds*))

  /**
   * Create an inline derived table from this table
   */
  override def whereExists(select: Select[?]): FilmActor = where(DSL.exists(select))

  /**
   * Create an inline derived table from this table
   */
  override def whereNotExists(select: Select[?]): FilmActor = where(DSL.notExists(select))
}
