/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.skala.db.tables.records


import java.lang.Long
import java.lang.String

import org.jooq.demo.skala.db.tables.ActorInfo
import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
class ActorInfoRecord extends TableRecordImpl[ActorInfoRecord](ActorInfo.ACTOR_INFO) {

  /**
   * Setter for <code>public.actor_info.actor_id</code>.
   */
  def setActorId(value: Long): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>public.actor_info.actor_id</code>.
   */
  def getActorId: Long = get(0).asInstanceOf[Long]

  /**
   * Setter for <code>public.actor_info.first_name</code>.
   */
  def setFirstName(value: String): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>public.actor_info.first_name</code>.
   */
  def getFirstName: String = get(1).asInstanceOf[String]

  /**
   * Setter for <code>public.actor_info.last_name</code>.
   */
  def setLastName(value: String): Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>public.actor_info.last_name</code>.
   */
  def getLastName: String = get(2).asInstanceOf[String]

  /**
   * Setter for <code>public.actor_info.film_info</code>.
   */
  def setFilmInfo(value: String): Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>public.actor_info.film_info</code>.
   */
  def getFilmInfo: String = get(3).asInstanceOf[String]

  /**
   * Create a detached, initialised ActorInfoRecord
   */
  def this(actorId : Long, firstName : String, lastName : String, filmInfo : String) = {
    this()

    this.setActorId(actorId)
    this.setFirstName(firstName)
    this.setLastName(lastName)
    this.setFilmInfo(filmInfo)
    resetTouchedOnNotNull()
  }

  /**
   * Create a detached, initialised ActorInfoRecord
   */
  def this(value: org.jooq.demo.skala.db.tables.pojos.ActorInfo) = {
    this()

    if (value != null) {
      this.setActorId(value.getActorId)
      this.setFirstName(value.getFirstName)
      this.setLastName(value.getLastName)
      this.setFilmInfo(value.getFilmInfo)
      resetTouchedOnNotNull()
    }
  }
}
