/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.skala.db.tables.records


import java.lang.Boolean
import java.lang.Integer
import java.lang.Long
import java.lang.String
import java.time.LocalDate
import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.demo.skala.db.tables.Customer
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
class CustomerRecord extends UpdatableRecordImpl[CustomerRecord](Customer.CUSTOMER) {

  /**
   * Setter for <code>public.customer.customer_id</code>.
   */
  def setCustomerId(value: Long): Unit = {
    set(0, value)
  }

  /**
   * Getter for <code>public.customer.customer_id</code>.
   */
  def getCustomerId: Long = get(0).asInstanceOf[Long]

  /**
   * Setter for <code>public.customer.store_id</code>.
   */
  def setStoreId(value: Long): Unit = {
    set(1, value)
  }

  /**
   * Getter for <code>public.customer.store_id</code>.
   */
  def getStoreId: Long = get(1).asInstanceOf[Long]

  /**
   * Setter for <code>public.customer.first_name</code>.
   */
  def setFirstName(value: String): Unit = {
    set(2, value)
  }

  /**
   * Getter for <code>public.customer.first_name</code>.
   */
  def getFirstName: String = get(2).asInstanceOf[String]

  /**
   * Setter for <code>public.customer.last_name</code>.
   */
  def setLastName(value: String): Unit = {
    set(3, value)
  }

  /**
   * Getter for <code>public.customer.last_name</code>.
   */
  def getLastName: String = get(3).asInstanceOf[String]

  /**
   * Setter for <code>public.customer.email</code>.
   */
  def setEmail(value: String): Unit = {
    set(4, value)
  }

  /**
   * Getter for <code>public.customer.email</code>.
   */
  def getEmail: String = get(4).asInstanceOf[String]

  /**
   * Setter for <code>public.customer.address_id</code>.
   */
  def setAddressId(value: Long): Unit = {
    set(5, value)
  }

  /**
   * Getter for <code>public.customer.address_id</code>.
   */
  def getAddressId: Long = get(5).asInstanceOf[Long]

  /**
   * Setter for <code>public.customer.activebool</code>.
   */
  def setActivebool(value: Boolean): Unit = {
    set(6, value)
  }

  /**
   * Getter for <code>public.customer.activebool</code>.
   */
  def getActivebool: Boolean = get(6).asInstanceOf[Boolean]

  /**
   * Setter for <code>public.customer.create_date</code>.
   */
  def setCreateDate(value: LocalDate): Unit = {
    set(7, value)
  }

  /**
   * Getter for <code>public.customer.create_date</code>.
   */
  def getCreateDate: LocalDate = get(7).asInstanceOf[LocalDate]

  /**
   * Setter for <code>public.customer.last_update</code>.
   */
  def setLastUpdate(value: LocalDateTime): Unit = {
    set(8, value)
  }

  /**
   * Getter for <code>public.customer.last_update</code>.
   */
  def getLastUpdate: LocalDateTime = get(8).asInstanceOf[LocalDateTime]

  /**
   * Setter for <code>public.customer.active</code>.
   */
  def setActive(value: Integer): Unit = {
    set(9, value)
  }

  /**
   * Getter for <code>public.customer.active</code>.
   */
  def getActive: Integer = get(9).asInstanceOf[Integer]

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  override def key: Record1[Long] = super.key.asInstanceOf[ Record1[Long] ]

  /**
   * Create a detached, initialised CustomerRecord
   */
  def this(customerId : Long, storeId : Long, firstName : String, lastName : String, email : String, addressId : Long, activebool : Boolean, createDate : LocalDate, lastUpdate : LocalDateTime, active : Integer) = {
    this()

    this.setCustomerId(customerId)
    this.setStoreId(storeId)
    this.setFirstName(firstName)
    this.setLastName(lastName)
    this.setEmail(email)
    this.setAddressId(addressId)
    this.setActivebool(activebool)
    this.setCreateDate(createDate)
    this.setLastUpdate(lastUpdate)
    this.setActive(active)
    resetTouchedOnNotNull()
  }

  /**
   * Create a detached, initialised CustomerRecord
   */
  def this(customerId : Long, storeId : Long, firstName : String, lastName : String, email : String, addressId : Long, activebool : Boolean, createDate : LocalDate, active : Integer) = {
    this()

    this.setCustomerId(customerId)
    this.setStoreId(storeId)
    this.setFirstName(firstName)
    this.setLastName(lastName)
    this.setEmail(email)
    this.setAddressId(addressId)
    this.setActivebool(activebool)
    this.setCreateDate(createDate)
    this.setActive(active)
    resetTouchedOnNotNull()
  }

  /**
   * Create a detached, initialised CustomerRecord
   */
  def this(value: org.jooq.demo.skala.db.tables.pojos.Customer) = {
    this()

    if (value != null) {
      this.setCustomerId(value.getCustomerId)
      this.setStoreId(value.getStoreId)
      this.setFirstName(value.getFirstName)
      this.setLastName(value.getLastName)
      this.setEmail(value.getEmail)
      this.setAddressId(value.getAddressId)
      this.setActivebool(value.getActivebool)
      this.setCreateDate(value.getCreateDate)
      this.setLastUpdate(value.getLastUpdate)
      this.setActive(value.getActive)
      resetTouchedOnNotNull()
    }
  }
}
