/*
 * This file is generated by jOOQ.
 */
package org.jooq.demo.kotlin.db.tables.pojos


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class Rental(
    val rentalId: Long? = null,
    val rentalDate: LocalDateTime? = null,
    val inventoryId: Long? = null,
    val customerId: Long? = null,
    val returnDate: LocalDateTime? = null,
    val staffId: Long? = null,
    val lastUpdate: LocalDateTime? = null
): Serializable {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other === null)
            return false
        if (this::class != other::class)
            return false
        val o: Rental = other as Rental
        if (this.rentalId === null) {
            if (o.rentalId !== null)
                return false
        }
        else if (this.rentalId != o.rentalId)
            return false
        if (this.rentalDate === null) {
            if (o.rentalDate !== null)
                return false
        }
        else if (this.rentalDate != o.rentalDate)
            return false
        if (this.inventoryId === null) {
            if (o.inventoryId !== null)
                return false
        }
        else if (this.inventoryId != o.inventoryId)
            return false
        if (this.customerId === null) {
            if (o.customerId !== null)
                return false
        }
        else if (this.customerId != o.customerId)
            return false
        if (this.returnDate === null) {
            if (o.returnDate !== null)
                return false
        }
        else if (this.returnDate != o.returnDate)
            return false
        if (this.staffId === null) {
            if (o.staffId !== null)
                return false
        }
        else if (this.staffId != o.staffId)
            return false
        if (this.lastUpdate === null) {
            if (o.lastUpdate !== null)
                return false
        }
        else if (this.lastUpdate != o.lastUpdate)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.rentalId === null) 0 else this.rentalId.hashCode())
        result = prime * result + (if (this.rentalDate === null) 0 else this.rentalDate.hashCode())
        result = prime * result + (if (this.inventoryId === null) 0 else this.inventoryId.hashCode())
        result = prime * result + (if (this.customerId === null) 0 else this.customerId.hashCode())
        result = prime * result + (if (this.returnDate === null) 0 else this.returnDate.hashCode())
        result = prime * result + (if (this.staffId === null) 0 else this.staffId.hashCode())
        result = prime * result + (if (this.lastUpdate === null) 0 else this.lastUpdate.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Rental (")

        sb.append(rentalId)
        sb.append(", ").append(rentalDate)
        sb.append(", ").append(inventoryId)
        sb.append(", ").append(customerId)
        sb.append(", ").append(returnDate)
        sb.append(", ").append(staffId)
        sb.append(", ").append(lastUpdate)

        sb.append(")")
        return sb.toString()
    }
}
